version: '3'
services:
  nodered:
    image: nodered/node-red-docker:v8
    ports:
    - 1880:1880
    volumes:
    - .:/local # Your local working copy
    - ./data:/data # Persist configuration between sessions